from django.urls import path

from . import views

urlpatterns = [
    path('setup/', views.setup_welcome, name='setup_welcome'),
    path('', views.home, name='home'),
    path('notifications/', views.notifications_feed, name='notifications_feed'),
    path('notifications/read-all/', views.notifications_mark_all_read, name='notifications_mark_all_read'),
    path('notifications/clear-all/', views.notifications_clear_all, name='notifications_clear_all'),
    path('settings/', views.app_settings, name='app_settings'),
    path('settings/connectors/', views.connector_settings, name='connector_settings'),
    path('settings/admin/', views.alshival_admin, name='alshival_admin'),
    path('settings/api-keys/account/create/', views.create_account_api_key_item, name='create_account_api_key_item'),
    path('wiki/', views.wiki, name='wiki'),
    path('wiki/editor/new/', views.wiki_editor_new, name='wiki_editor_new'),
    path('wiki/editor/<int:page_id>/', views.wiki_editor, name='wiki_editor'),
    path('wiki/pages/create/', views.wiki_create_page, name='wiki_create_page'),
    path('wiki/pages/<int:page_id>/update/', views.wiki_update_page, name='wiki_update_page'),
    path('wiki/pages/<int:page_id>/delete/', views.wiki_delete_page, name='wiki_delete_page'),
    path('team-directory/', views.team_directory, name='team_directory'),
    path('team-directory/teams/create/', views.team_directory_create_team, name='team_directory_create_team'),
    path('team-directory/teams/<int:team_id>/rename/', views.team_directory_rename_team, name='team_directory_rename_team'),
    path('team-directory/teams/<int:team_id>/delete/', views.team_directory_delete_team, name='team_directory_delete_team'),
    path('team-directory/teams/<int:team_id>/members/update/', views.team_directory_update_team_members, name='team_directory_update_team_members'),
    path('team-directory/teams/<int:team_id>/members/add/', views.team_directory_add_team_member, name='team_directory_add_team_member'),
    path('team-directory/teams/<int:team_id>/members/<int:user_id>/remove/', views.team_directory_remove_team_member, name='team_directory_remove_team_member'),
    path('team-directory/users/create/', views.team_directory_create_user, name='team_directory_create_user'),
    path('team-directory/users/<int:user_id>/update/', views.team_directory_update_user, name='team_directory_update_user'),
    path('team-directory/users/<int:user_id>/delete/', views.team_directory_delete_user, name='team_directory_delete_user'),
    path('team-directory/users/<int:user_id>/permissions/', views.team_directory_update_user_permissions, name='team_directory_update_user_permissions'),
    path('team-directory/users/invite/', views.team_directory_invite_user, name='team_directory_invite_user'),
    path('resources/', views.resources, name='resources'),
    path('resources/ssh-keys/add/', views.add_ssh_credential_item, name='add_ssh_credential_item'),
    path('resources/ssh-keys/<str:credential_id>/delete/', views.delete_ssh_credential_item, name='delete_ssh_credential_item'),
    path('resources/ssh-keys/global/<int:credential_id>/delete/', views.delete_global_ssh_credential_item, name='delete_global_ssh_credential_item'),
    path('u/<str:username>/resources/<str:resource_uuid>/logs/', views.resource_logs_ingest, name='resource_logs_ingest'),
    path('team/<str:team_name>/resources/<str:resource_uuid>/logs/', views.team_resource_logs_ingest, name='team_resource_logs_ingest'),
    path('u/<str:username>/resources/<uuid:resource_uuid>/notes/add/', views.resource_note_add, name='resource_note_add'),
    path('team/<str:team_name>/resources/<uuid:resource_uuid>/notes/add/', views.team_resource_note_add, name='team_resource_note_add'),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/notes/attachments/<int:attachment_id>/',
        views.resource_note_attachment,
        name='resource_note_attachment',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/notes/attachments/<int:attachment_id>/',
        views.team_resource_note_attachment,
        name='team_resource_note_attachment',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/check/',
        views.check_resource_health_detail,
        name='check_resource_health_detail',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/check/',
        views.team_check_resource_health_detail,
        name='team_check_resource_health_detail',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/alerts/settings/update/',
        views.update_resource_alert_settings,
        name='update_resource_alert_settings',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/alerts/settings/update/',
        views.team_update_resource_alert_settings,
        name='team_update_resource_alert_settings',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/api-keys/create/',
        views.create_resource_api_key_item,
        name='create_resource_api_key_item',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/api-keys/create/',
        views.team_create_resource_api_key_item,
        name='team_create_resource_api_key_item',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/api-keys/<int:key_id>/revoke/',
        views.revoke_resource_api_key_item,
        name='revoke_resource_api_key_item',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/api-keys/<int:key_id>/revoke/',
        views.team_revoke_resource_api_key_item,
        name='team_revoke_resource_api_key_item',
    ),
    path('u/<str:username>/resources/<uuid:resource_uuid>/', views.resource_detail, name='resource_detail'),
    path('team/<str:team_name>/resources/<uuid:resource_uuid>/', views.team_resource_detail, name='team_resource_detail'),
    path('resources/add/', views.add_resource_item, name='add_resource_item'),
    path('resources/<int:resource_id>/edit/', views.edit_resource_item, name='edit_resource_item'),
    path('resources/<int:resource_id>/delete/', views.delete_resource_item, name='delete_resource_item'),
    path('resources/<int:resource_id>/check/', views.check_resource_health, name='check_resource_health'),
    path('chat/ask/', views.ask_alshival_chat, name='ask_alshival_chat'),
]
